[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration des formulaires Netlify
[forms]
  from = "contact"
  to = "guillaumel1103@gmail.com"
  subject = "Nouveau message depuis votre portfolio"

# Configuration des notifications
[[plugins]]
  package = "netlify-plugin-form-submissions"

  [plugins.inputs]
    email = "guillaumel1103@gmail.com" 